### ISSUE TITLE
ROS not able to create resources that name contians hyphen

### ISSUE THREAD

**Issue by Blankll** [aliyun/aliyun-cli#1004]
* **Command Format**:
ROS yaml
```yaml
  ApiGateway:
    Type: 'ALIYUN::ApiGateway::Group'
    Properties:
      GroupName: !Join [ '-', [ !Ref AppName, 'api-gateway', !Ref AppEnv] ]
```
execute command to create stack:
```bash
 ros CreateStack \
--StackName $STACK_NAME \
--TemplateBody "$(cat ./iac/stack.yml)" \
--Parameters ParameterKey=AppName,ParameterValue=$APP_NAME,ParameterKey=AppEnv,ParameterValue=$APP_ENV

```
* **Execution Command**:
resource can create successfully since I can create ApiGateway::Group resource that GroupName contains `-` through the web console 
* **Output**:
Message: Property error: : Resources.ApiGatewayApi.Properties.ApiName: : Resource [ApiGatewayApi]: xxx-api-gateway-api-dev is invalid. Its length should be 4-50 characters, and should begin with upper or lower case letter or Chinese. Numbers or "_" are included.
