### ISSUE TITLE
添加支持内网endpoint预配置或使用参数自动拼接endpoint

### ISSUE THREAD

**Issue by luyi0521** [aliyun/aliyun-cli#342]
在金融云内网，指定region-id后，因go-sdk中没有内置金融云相关endpoint
每个请求需要独立指定endpoint
建议支持读取配置文件，获取预配置的产品对应endpoint

举个栗子：
```yaml
ecs: 
  vpc: 
    cn-shanghai-finance-1: 
      endpoint: ecs-vpc.cn-shanghai-finance-1.aliyuncs.com
    cn-shenzhen-finance-1: 
      endpoint: ecs-vpc.cn-shenzhen-finance-1.aliyuncs.com
slb: 
  vpc: 
    cn-shanghai-finance-1: 
      endpoint: slb-vpc.cn-shanghai-finance-1.aliyuncs.com
    cn-shenzhen-finance-1: 
      endpoint: slb-vpc.cn-shenzhen-finance-1.aliyuncs.com
```

或者
参考go-sdk中的拼接endpoint 的样式，通过添加参数自动拼接endpoint
<product>-<network>.<region_id>.aliyuncs.com
这个可以覆盖大多数的产品
我在用go-sdk 访问内网sts服务的时候碰到没有内置endpoint
做的调整是在初始化请求客户端之后设定Network为vpc
client.Network = "vpc"
就可以访问正确的endpoint了（"sts-vpc.cn-shanghai-finance-1.aliyuncs.com"）
